LibDB/Controllers/HomeController.cs
using LibDB.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibDB.Controllers
{
    public class HomeController : Controller
    {
        IRepository<Organization> repository;
        IRepository<TestBase> repositoryAuths;

        public HomeController(IRepository<Organization> repo, IRepository<TestBase> repoA)
        {
            repository = repo;
            repositoryAuths = repoA;
        }

        public ActionResult Index()
        {
            var model = repository.GetAll().First();
            ViewBag.Organization = model;

            var modelA = repositoryAuths.GetAll();

            return View(modelA);
        }
    }
}

LibDB/Controllers/TestBasesController.cs
using LibDB.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibDB.Controllers
{
    public class TestBasesController : Controller
    {
        IRepository<TestBase> repository;

        public TestBasesController(IRepository<TestBase> repo)
        {
            repository = repo;
        }

        // GET: TestAuths/Details/5
        public ActionResult Details(int id)
        {
            return View(repository.Get(id));
        }

        // GET: TestAuths/Create
        public ActionResult Create()
        {
            var mbase = new TestBase();
            return View(mbase);
        }

        // POST: TestAuths/Create
        [HttpPost]
        public ActionResult Create(TestBase mbase)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repository.Create(mbase);
                    return RedirectToAction("Index","Home");
                }
                catch
                {
                    return View();
                }
            }
            else return View(mbase);
        }

        // GET: TestAuths/Edit/5
        public ActionResult Edit(int id)
        {
            return View(repository.Get(id));
        }

        // POST: TestAuths/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TestBase mbase)
        {
            try
            {
                // TODO: Add update logic here
                repository.Update(mbase);
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: TestAuths/Delete/5
        public ActionResult Delete(int id)
        {
            return View(repository.Get(id));
        }

        // POST: TestAuths/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                repository.Delete(id);
                return RedirectToAction("Index","Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

LibDB/Controllers/TestCardsController.cs
using LibDB.Models;
using LibDB.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibDB.Controllers
{
    public class TestCardsController : Controller
    {
        IRepository<TestCard> repositoryCards;
        IRepository<TestBase> repositoryBases;

        int pageSize = 7;

        public TestCardsController(IRepository<TestCard> repoCard, IRepository<TestBase> repoBase)
        {
            repositoryCards = repoCard;
            repositoryBases = repoBase;
        }

        public ActionResult List(string maingroup, string group,string searchtext, int page = 1)
        {
            ViewBag.ListItem = repositoryBases.GetAll();

            PageListViewModel<TestCard> model;

            if (!string.IsNullOrEmpty(maingroup))
            {
                if (!string.IsNullOrEmpty(searchtext))
                {
                    var nlst = repositoryCards.GetAll().Where(a => a.BaseId == Convert.ToInt32(maingroup) && group == null
                                                            || a.Year == Convert.ToInt32(group))
                                                            .OrderBy(d => d.Title)
                                                            .OrderByDescending(d => d.Year);

                    var lstnew = nlst.Where(s => s.Title.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Header) && s.Header.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Body) && s.Body.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Description) && s.Description.Contains(searchtext)
                    );

                    model = PageListViewModel<TestCard>.CreatePage(lstnew, page, pageSize);

                }
                else
                {
                    var nlst = repositoryCards.GetAll().Where(a => a.BaseId == Convert.ToInt32(maingroup) && group == null
                                                            || a.BaseId == Convert.ToInt32(maingroup) && a.Year == Convert.ToInt32(group))
                                                            .OrderBy(d => d.Title)
                                                            .OrderByDescending(d => d.Year);

                    model = PageListViewModel<TestCard>.CreatePage(nlst, page, pageSize);
                }
            }
            else
            {
                if (!string.IsNullOrEmpty(searchtext))
                {
                    var nlst = repositoryCards.GetAll().Where(a => group == null
                                        || a.Year == Convert.ToInt32(group))
                                        .OrderBy(d => d.Title)
                                        .OrderByDescending(d => d.Year);

                    var lstnew = nlst.Where(s => s.Title.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Header) && s.Header.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Body) && s.Body.Contains(searchtext)
                    || !string.IsNullOrEmpty(s.Description) && s.Description.Contains(searchtext)
                    );

                    model = PageListViewModel<TestCard>.CreatePage(lstnew, page, pageSize);

                }
                else
                {
                    var nlst = repositoryCards.GetAll().Where(a => group == null
                                        || a.Year == Convert.ToInt32(group))
                                        .OrderBy(d => d.Title)
                                        .OrderByDescending(d => d.Year);

                    model = PageListViewModel<TestCard>.CreatePage(nlst, page, pageSize);
                }
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView("ListPartial", model);
            }


            return View(model);
        }

        // GET: TestCards/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: TestCards/Create
        public ActionResult Create(string mbase)
        {
            var card = new TestCard();
            int mainbase = 1;
            if(Int32.TryParse(mbase,out mainbase))
            {
                card.BaseId = mainbase;
            }

            card.Year = DateTime.Now.Year;
            ViewBag.ListItem = repositoryBases.GetAll();
            return View(card);
        }

        // POST: TestCards/Create
        [HttpPost]
        public ActionResult Create(TestCard card,string mbase)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repositoryCards.Create(card);
                    return RedirectToAction("List", new { maingroup = mbase });
                }
                catch
                {
                    return View();
                }
            }
            else return View(card);
        }

        // GET: TestCards/Edit/5
        public ActionResult Edit(int id)
        {
            ViewBag.ListItem = repositoryBases.GetAll();
            return View(repositoryCards.Get(id));
        }

        // POST: TestCards/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TestCard card)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    repositoryCards.Update(card);
                    return RedirectToAction("List");
                }
                catch
                {
                    return View();
                }
            }
            else return View(card);
        }

        // GET: TestCards/Delete/5
        public ActionResult Delete(int id)
        {
            return View(repositoryCards.Get(id));
        }

        // POST: TestCards/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                repositoryCards.Delete(id);
                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        public PartialViewResult Side(string maingroup)
        {
            var databases = repositoryBases
                .GetAll();

            var group = repositoryCards
                        .GetAll()
                        .Where(a => maingroup == null || maingroup == "Все"
                        || a.BaseId == Convert.ToInt32(maingroup))
                        .OrderByDescending(d => d.Year)
                        .Select(d => d.Year)
                        .Distinct();

            ViewBag.Years = group;

            return PartialView(databases);
        }
    }
}

LibDB/Views/Home/Index.cshtml
@model IEnumerable<LibDB.DAL.TestBase>
@using System.Text;
@{
    ViewBag.Title = "Базы данных библиотеки";
}
<h2 class="mt-5">Базы данных библиотеки</h2>
<hr />
<div class="row">
    <div class="col">
        <div class="row">
            <div class="col-md-12">
                @using (Html.BeginForm())
                {
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" id="searchtext" name="searchbase" placeholder="Поиск..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <input type="submit" class="btn btn-dark" value="Поиск" />
                            @{
                                if (User.Identity.IsAuthenticated)
                                {
                                    if (User.IsInRole("admin"))
                                    {
                                        @Html.ActionLink("Добавить", "Create", "TestBases", null, new { @class = "btn btn-success" })
                                    }
                                }
                            }
                        </div>
                    </div>
                }
            </div>
            @{
                foreach (var item in Model)
                {
                    <div class="col-md-12">
                        <div class="card shadow-lg mb-3">
                            <p class="card-header text-uppercase">@item.Id. @item.Title</p>
                            @*<img src="~/Images/placeholder.png" class="card-img-top">*@
                            <div class="card-body">
                                <p class="card-text">@item.Description</p>
                            </div>
                            <div class="card-footer">
                                @{
                                    <div class="btn-group btn-group-sm pull-right" role="group" aria-label="Basic example">
                                        <a href="@Url.Action("List", "TestCards", new { maingroup = item.Id })" class="btn btn-dark">
                                            Просмотр
                                        </a>
                                        @if (User.Identity.IsAuthenticated)
                                        {
                                            if (User.IsInRole("admin"))
                                            {
                                                <a href="@Url.Action("Edit", "TestBases", new { id = item.Id })" class="btn btn-primary">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a href="@Url.Action("Delete", "TestBases", new { id = item.Id })" class="btn btn-danger">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            }
                                        }
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
</div>